language: rust
dist: trusty
rust:
    - stable
sudo: required
addons:
  apt:
    packages:
        - libpcap-dev
        - musl-tools
        - musl-dev
        - musl
script:
  - |
      # uninstall the rust toolchain installed by travis, we are going to use rustup
      sh ~/rust/lib/rustlib/uninstall.sh &&
      export PATH=$PATH:$HOME/.cargo/bin/ &&
      echo "Building static binary" &&
      sh extra/musl-build.sh &&
      echo "Building normal binary" &&
      CFLAGS="-I${PWD}/netmap/sys/" cargo build --verbose --target=`arch`-unknown-linux-gnu --release

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: jCgZtLtOUxk0I4pdqT8RcKVs1/epyR8zU1vQor0Zr1itkvr5bmhWsDPICeWo3Tli3YLYAzwe09Oma/DR73rHO7RoEZ6xnP1HmG0vfptDOpXiQqU5mVuUNJ/ms1PfwAQsB4a1aPD8rfWhpwdLAS6HoUScKc/wUW+F76iFeUhSvb52t8DuIo8NB2GWt2JC/byHsNKYa96DOnzDsyODeokX20GpoqMkewW2pz
  file: target/x86_64-unknown-linux-musl/release/syncookied
  on:
    tags: true
